opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - force_cast
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

included:
  - MyAwesomeLib/
  - MyAwesomeLibTests/
excluded:
  - Pods/
  - build/
  - scripts/
  - docs/

# Custom rules
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

trailing_whitespace:
  severity: warning
  ignores_empty_lines: true

# Commonly used rules
identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
    - t
    - e
    - f
    - g
    - h
    - w
    - z

function_body_length:
  warning: 40
  error: 100
  ignores_comments: true
  ignores_empty_functions: true

file_length:
  warning: 400
  error: 1000

# Style
force_cast:
  severity: error
force_unwrapping:
  severity: error

# Type body length
type_body_length:
  warning: 200
  error: 350

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting
nesting:
  type_level: 2
  function_level: 2

# Unused code
unused_closure_parameter:
  severity: warning
unused_enumerated:
  severity: warning
unused_optional_binding:
  severity: warning

# Comment rules
todo:
  severity: warning
