name: Build XCFramework
description: Build XCFramework for iOS and iOS Simulator

inputs:
  project_name:
    description: Name of the Xcode project or scheme
    required: true

  xcode-version:
    description: Xcode version to use (e.g., 16.4)
    required: true

outputs:
  xcframework_path:
    description: Final path to the generated XCFramework
    value: ${{ steps.build.outputs.xcframework_path }}

runs:
  using: "composite"
  steps:
    - name: Set Xcode version
      uses: ../set-xcode-version
      with:
        xcode-version: ${{ inputs.xcode-version }}
        
    - name: Build XCFramework
      id: build
      shell: bash
      run: |
        set -euo pipefail

        PROJECT_NAME="${{ inputs.project_name }}"
        BUILD_DIR="./build"

        echo "ðŸ› ï¸ Building XCFramework..."

        xcodebuild archive \
            -scheme "$PROJECT_NAME" \
            -configuration Release \
            -destination 'generic/platform=iOS Simulator' \
            -archivePath "$BUILD_DIR/${PROJECT_NAME}.framework-iphonesimulator.xcarchive" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES | xcbeautify

        xcodebuild archive \
            -scheme "$PROJECT_NAME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath "$BUILD_DIR/${PROJECT_NAME}.framework-iphoneos.xcarchive" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES | xcbeautify

        XCFRAMEWORK_PATH="$BUILD_DIR/${PROJECT_NAME}.xcframework"

        xcodebuild -create-xcframework \
            -framework "$BUILD_DIR/${PROJECT_NAME}.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/${PROJECT_NAME}.framework" \
            -framework "$BUILD_DIR/${PROJECT_NAME}.framework-iphoneos.xcarchive/Products/Library/Frameworks/${PROJECT_NAME}.framework" \
            -output "$XCFRAMEWORK_PATH"

        echo "âœ… XCFramework built successfully"
        echo "xcframework_path=$XCFRAMEWORK_PATH" >> "$GITHUB_OUTPUT"
